apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmplan-dashboard-backend #The name of the Kubernetes
        #Deployment to be created in the Kubernetes cluster
  namespace: farmplan
  labels:
    app: farmplan-dashboard-backend
  annotations:
    etce-server-volume-backup: /app/database
spec:
  replicas: 1 #The number of pods to be created in the
   #Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: farmplan-dashboard-backend
  template:
    metadata:
      labels:
        app: farmplan-dashboard-backend
    spec:
      imagePullSecrets:
      - name: docker-registry-private
      containers:
      - name: farmplan-dashboard-backend
        image: registry.etce.isse.tu-clausthal.de/etce-lab/farmplan-dashboard-backend:latest
        ports:
        - containerPort: 5000 #The port for the flask container
        volumeMounts:
            - name: farmplan-env
              mountPath: /app/environment
              readOnly: true
      volumes:
      - name: farmplan-env
        configMap:
          name: farmplan-env
          items:
            - key: .env
              path: .env
