apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created
  #in the Kubernetes cluster
  name: farmplan-dashboard-backend-service
  namespace: farmplan
spec:
  selector:
    app: farmplan-dashboard-backend
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 11111 #Service port
    targetPort: 5000
